##server##
server:
  port: 9898
  servlet:
    context-path: /myapp
##web mvc##
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
##datasource##
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
##jpa##
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL55Dialect
        format-sql: true